### Login and get token
# @name login
POST http://localhost:{{$dotenv PORT}}/auth/login
Content-Type: application/json

{
    "email": "trainee@email.com",
    "password": "password"
}


###
@baseURL = http://localhost:{{$dotenv PORT}}/training
@token = {{login.response.headers.Set-Cookie}}
@userId = {{login.response.body.data._id}}

### Create Training

POST {{baseURL}}
Content-Type: application/json
Cookie: {{token}}



### Find Training By Id
@trainingId = 634958ef63349efcd70182a2
GET {{baseURL}}/{{trainingId}}



### Find Users Trainings By Id
GET {{baseURL}}/user/{{userId}}
#?page=1&size=1



### Find users trainings - ongoing
GET {{baseURL}}/user/{{userId}}/ongoing
#?page=1&size=1



### Find users trainings - ended
GET {{baseURL}}/user/{{userId}}/ended
#?page=1&size=1