### Login and get token
# @name login
POST http://localhost:{{$dotenv PORT}}/auth/login
Content-Type: application/json

{
    "email": "trainee@email.com",
    "password": "password"
}


###
@baseURL = http://localhost:{{$dotenv PORT}}/training
@token = {{login.response.headers.Set-Cookie}}
@sessionId = session_f622e5d1-3464-40f8-a70a-6514ffc5b69f

### Create Training

POST {{baseURL}}
Content-Type: application/json
Cookie: {{token}}




### Find Training By Id
@trainingId = 634958ef63349efcd70182a2
GET {{baseURL}}/{{trainingId}}




### Find Users Trainings By Id
@userId = 634951162681a66c5be77031
GET {{baseURL}}/user/{{userId}}



### Find users trainings - ongoing
@userId = 634951162681a66c5be77031

GET {{baseURL}}/user/{{userId}}/ongoing
Content-Type: application/json
Cookie: {{token}}


### Find users trainings - ended
@userId = 634951162681a66c5be77031

GET {{baseURL}}/user/{{userId}}/ended
Content-Type: application/json
Cookie: {{token}}